# Generated by Django 2.2.8 on 2020-01-31 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='empresa',
        ),
    ]
