# Generated by Django 2.2.8 on 2020-02-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_factura_s'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='s',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
